"""K-space stargate graph from bundled static data (generated from the SDE).

Answers the radar's geometry questions: how many gate jumps between two
systems, which systems form the bubble around home, and what system a chat
token like "K7D-II" or the shorthand "P-Z" refers to.

Generated by ``tools/gen_map_graph.py`` into ``data/map_graph.json``; same
lazy-loader contract as ``weaponrange``: missing/corrupt data turns the
feature off silently instead of crashing.
"""
from __future__ import annotations

import json
import re
import sys
from collections import deque
from pathlib import Path
from typing import Dict, Iterable, Optional, Set, Tuple

_DATA_REL = ("data", "map_graph.json")
_names: Optional[Dict[int, Tuple[str, float]]] = None   # id -> (name, sec)
_by_lower: Dict[str, int] = {}
_adj: Dict[int, Tuple[int, ...]] = {}
_failed = False

_TOKEN_CLEAN = re.compile(r"^[\s\*\.,;:!\?\(\)\[\]]+|[\s\*\.,;:!\?\(\)\[\]]+$")


def load() -> bool:
    """Lazy-load the bundled graph; False (and stays off) on any failure."""
    global _names, _failed
    if _names is not None:
        return True
    if _failed:
        return False
    candidates = [Path(__file__).resolve().parent.joinpath(*_DATA_REL)]
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        candidates.append(Path(meipass, "eve_localwatcher", *_DATA_REL))
    for f in candidates:
        try:
            if f.is_file():
                raw = json.loads(f.read_text(encoding="utf-8"))
                _install(raw)
                return True
        except Exception:
            break
    _failed = True
    return False


def _install(raw: dict) -> None:
    """Build the runtime indexes (also used by tests to inject a tiny graph)."""
    global _names, _by_lower, _adj, _failed
    _names = {int(k): (v[0], float(v[1])) for k, v in raw["systems"].items()}
    _by_lower = {name.lower(): sid for sid, (name, _s) in _names.items()}
    _adj = {int(k): tuple(int(x) for x in v) for k, v in raw.get("adj", {}).items()}
    _failed = False


def name_for_id(system_id: int) -> Optional[str]:
    if not load():
        return None
    e = _names.get(int(system_id))
    return e[0] if e else None


def security(system_id: int) -> Optional[float]:
    if not load():
        return None
    e = _names.get(int(system_id))
    return e[1] if e else None


def id_for_name(name: str) -> Optional[int]:
    if not load() or not name:
        return None
    return _by_lower.get(name.strip().lower())


def resolve_system(token: str,
                   restrict_ids: Optional[Iterable[int]] = None) -> Optional[int]:
    """System id for a chat/UI token.

    Exact (case-insensitive) match always works. Prefix matching is only
    attempted within ``restrict_ids`` (the radar bubble) — there a shorthand
    like "P-Z" is unambiguous, map-wide it is not. 0 or ≥2 prefix hits → None.
    """
    if not load():
        return None
    tok = _TOKEN_CLEAN.sub("", token or "")
    if len(tok) < 2:
        return None
    exact = _by_lower.get(tok.lower())
    if exact is not None:
        return exact
    if restrict_ids is None:
        return None
    low = tok.lower()
    hits = [sid for sid in restrict_ids
            if (_names.get(int(sid)) or ("",))[0].lower().startswith(low)]
    return int(hits[0]) if len(hits) == 1 else None


def distance(a: int, b: int, max_hops: int = 8) -> Optional[int]:
    """Gate jumps a→b via bounded BFS; None if unreachable within max_hops."""
    if not load():
        return None
    a, b = int(a), int(b)
    if a == b:
        return 0
    seen = {a}
    frontier = deque([(a, 0)])
    while frontier:
        node, d = frontier.popleft()
        if d >= max_hops:
            continue
        for nb in _adj.get(node, ()):
            if nb == b:
                return d + 1
            if nb not in seen:
                seen.add(nb)
                frontier.append((nb, d + 1))
    return None


def systems_within(origin: int, n: int) -> Dict[int, int]:
    """{system_id: jumps} for everything within n gate jumps (origin at 0)."""
    if not load():
        return {}
    origin = int(origin)
    if origin not in _names:
        return {}
    out = {origin: 0}
    frontier = deque([(origin, 0)])
    while frontier:
        node, d = frontier.popleft()
        if d >= n:
            continue
        for nb in _adj.get(node, ()):
            if nb not in out:
                out[nb] = d + 1
                frontier.append((nb, d + 1))
    return out
